name:                DailyReporter
version:             0.1.0.0
github:              "jhgarner/DailyReporter"
license:             MIT
author:              "Jackson Garner"
maintainer:          "jhgarner@mymail.mines.edu"
copyright:           "2018 Jackson Garner"

extra-source-files:
- README.md
- ChangeLog.md
- LICENSE
- data/*/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jhgarner/DailyReporter#readme>

dependencies:
- aeson
- lens-aeson
- http-conduit
- bytestring
- text
- time
- lens
- scalpel
- feed >= 1.3.2.1
- containers
- hashable
- conduit-extra
- vector
- fast-tagsoup
- tagsoup
- recursion-schemes
- indexed-traversable
- deriving-aeson
- PyF
- req
- cleff
# - cleff-plugin Add this back if it gets updated
- modern-uri
- unliftio
- http-api-data
- file-embed

language: GHC2021

default-extensions:
- BlockArguments
- TypeFamilies
- GADTs
- LambdaCase
- TupleSections
- OverloadedStrings
- DataKinds
- PartialTypeSignatures
- QualifiedDo
- QuasiQuotes
- ScopedTypeVariables
- DerivingStrategies
- DerivingVia

internal-libraries:
  CustomPrelude:
    source-dirs: prelude
    dependencies:
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
        - (Prelude as BasePrelude)
        - ""

library:
  source-dirs: src
  ghc-options:
    # - -fplugin=Cleff.Plugin
    - -Wno-partial-type-signatures
  dependencies:
  - name: base
    version: ">= 4.7 && < 5"
    mixin:
    - hiding (Prelude)
  - name: CustomPrelude

executables:
  DailyReporter-exe:
    main:                Main.hs
    source-dirs:         app
    # cc-options: -static
    # ld-options: -static -pthread
    ghc-options:
    - -threaded
    - -rtsopts
    # - -static
    - -with-rtsopts=-N
    - -W
    - -Wno-partial-type-signatures
    dependencies:
    - base >= 4.7 && < 5
    - DailyReporter

tests:
  DailyReporter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-partial-type-signatures
    dependencies:
    - name: base
      version: ">= 4.7 && < 5"
      mixin:
      - hiding (Prelude)
    - DailyReporter
    - hspec
    - name: CustomPrelude
    build-tools:
    - hspec-discover
