{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}

module Sources.Apod (apod) where

import Data.Map (Map, singleton)
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import Data.Text.Encoding (decodeUtf8)
import Parser.JsonParser (extractJson)
import PyF (fmt)
import Utils (getHttp)
import qualified Data.ByteString

-- | The final html text generated by apod.nasa.gov source.
--  Astronomy Picture Of the Day. Maybe videos some days, which can never quite
--  be included into an email (iframes...)
apod :: Text -> IO (Map Text Text)
apod apodApikey = do
  json <- getHttp [fmt|https://api.nasa.gov/planetary/apod?api_key={apodApikey}|]
  parser <- Data.ByteString.readFile "parsers/apod.json"
  pure $ fromMaybe (singleton "*title" "no picture today") $ extractJson parser json