{-# LANGUAGE OverloadedStrings #-}

module Sources.Xkcd (xkcd) where

import qualified Data.ByteString
import Data.Map (Map, insert, toList)
import Data.Text (Text)
import Parser.HtmlParser (extractHtml)
import Utils (getTitleAndSummary)

-- | The final html text generated by scraping xkcd RSS feed.
xkcd :: IO (Map Text Text)
xkcd = do
  guide <- Data.ByteString.readFile "parsers/xkcd.json"
  (title, summary) <- getTitleAndSummary "https://xkcd.com/atom.xml"
  pure $ insert "*title" title $ extractHtml guide summary