
module Sources.Xkcd (xkcd) where

import Parser.HtmlParser (extractHtml)
import Network.Class
import File.Class

-- | The final html text generated by scraping xkcd RSS feed.
xkcd :: [Network, File, NetworkError] :>> es => Eff es (Map Text Text)
xkcd = do
  guide <- getFile "parsers/xkcd.json"
  site <- get (https "xkcd.com") mempty
  pure $ extractHtml guide site