{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}

module Apod
  ( apod,
  )
where

import Config
import Data.HashMap.Strict (toList)
import Data.Maybe
import Data.Text
import Data.Text.IO
import Parser
import Utils
import Prelude hiding (readFile)
import Data.Aeson.KeyMap (toHashMapText)

-- | The final html text generated by apod.nasa.gov source.
--  Astronomy Picture Of the Day. Maybe videos some days, which can never quite
--  be included into an email (iframes...)
apod :: Config -> IO Text
apod Config {apodApikey} = do
  json <- getHttp $ unpack $ "https://api.nasa.gov/planetary/apod?api_key=" <> apodApikey
  parser <- readFile "parsers/apod.json"
  apodTemplate <- readFile "templates/Apod.html"
  pure $ maybe "" ((`template` apodTemplate) . toList) $ extractJson parser json

-- | Template for apod (templates/Apod.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/Apod.html"

-- | APOD source.
source :: Text -> IO Text
source apikey = getHttp $ unpack $ "https://api.nasa.gov/planetary/apod?api_key=" <> apikey
