{-# LANGUAGE OverloadedStrings #-}

module Apod
  ( apod
  ) where

import Data.Maybe
import Text.HTML.Scalpel

import Data.Text
import Data.Text.IO

import Utils

-- |The final html text generated by apod.nasa.gov source.
-- Astronomy Picture Of the Day. Maybe videos some days, which can never quite
-- be included into an email (iframes...)
apod :: IO Text
apod = do
    s <- scrapeSite
    h <- htmlS
    let replacements = fromMaybe [] s
    return $ template replacements h

-- |Template for apod (templates/Apod.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/Apod.html"

-- |Scrape site, but fix all the messed up <p> tags (all of them).
-- TODO: Look for a better way. Salvation.
scrapeSite :: IO (Maybe [(Text, Text)])
scrapeSite = do
  response <- replace "<p>" "</p><p>" <$> source
  return $ scrapeStringLike response scraper

-- |APOD source.
source :: IO Text
source = getHttp "https://apod.nasa.gov/apod/astropix.html"

-- |Scraper object for getting templating information in APOD.
scraper :: Scraper Text [(Text, Text)]
scraper = do
  img <- (!! 1) <$> attrs "href" "a"
  title <- html "b"
  explanation <- (!! 2) <$> texts "p"
  return $
      [("*img", img)
     , ("*title", title)
     , ("*exp", explanation)]
