{-# LANGUAGE OverloadedStrings #-}

module Ec
  ( ec
  ) where

import Data.Text
import Data.Text.IO
import Utils

-- |The final html text generated by existentialcomics RSS feed
ec :: IO Text
ec = do
  h <- htmlS
  (title, summary) <- getTitleAndSummary "https://existentialcomics.com/rss.xml"
  return (template
          [("*title", title)
         , ("*summary", summary)] h)

-- |Template file for existential comics (templates/Ec.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/Ec.html"
