{-# LANGUAGE OverloadedStrings #-}

module PDL
    ( pdl
    ) where

import Data.Maybe
import Data.Text
import Data.Text.IO
import Text.HTML.Scalpel
import Utils

-- |The final html text generated by scraping poorlydrawnlines.com as well as
-- |their RSS feeds
pdl :: IO Text
pdl = do
  h <- htmlS
  (title, _) <- getTitleAndSummary pdlFeed
  img <- scrapeImg <$> getHttp pdlURL
  return (template
          [("*title", title)
         , ("*img", img)] h)

-- |PDL feed URL
pdlFeed :: String
pdlFeed = "http://feeds.feedburner.com/PoorlyDrawnLines?format=xml"

-- |PDL website URL
pdlURL :: String
pdlURL = "http://www.poorlydrawnlines.com/"

-- |Get poorly drawn lines template (templates/PDL.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/PDL.html"

-- |Scraping logic for PDL
scrapeImg :: Text -> Text
scrapeImg s =
    fromMaybe "" .
    scrapeStringLike s .
    innerHTML $ "div" @: [hasClass "post"]
