{-# LANGUAGE OverloadedStrings #-}

module PDL
  ( pdl,
  )
where

import qualified Data.ByteString as B
import Data.Maybe
import Data.Text
import Data.Text.Encoding
import Data.Text.IO
import Text.HTML.Scalpel
import Text.Regex.Posix
import Utils
import Parser
import Data.HashMap.Strict (toList)

-- | The final html text generated by scraping poorlydrawnlines.com as well as
--  |their RSS feeds
pdl :: IO Text
pdl = do
  h <- htmlS
  -- Unfortunately the title is only in the RSS feed...
  title <- getTitle pdlFeed
  guide <- Data.Text.IO.readFile "parsers/pdl.json"
  html <- getHttp "https://poorlydrawnlines.com/"
  let result = toList $ fromJust $ extractHtml guide html
  pure $ template (("*title", title) : result) h

-- | PDL feed URL
pdlFeed :: String
pdlFeed = "http://feeds.feedburner.com/PoorlyDrawnLines"

-- | Get poorly drawn lines template (templates/PDL.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/PDL.html"
