{-# LANGUAGE OverloadedStrings #-}

module Qwantz
  ( qwantz
  ) where

import Data.Maybe
import Data.Text
import Data.Text.IO
import Text.HTML.Scalpel
import Utils

-- |The final html text generated by the qwantz feed.
-- We then proceed to scrape only the image and title.
qwantz :: IO Text
qwantz = do
  h <- htmlS
  (title, summary) <- getTitleAndSummary "http://www.qwantz.com/rssfeed.php"
  return (template
      [("*title", title)
     , ("*summary", scrapeImg summary)
     , ("*alt", scrapeAlt summary)] h)

-- |Get template for qwantz (templates/Qwantz.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/Qwantz.html"

-- |Scrape alt-text from qwantz
scrapeAlt :: Text -> Text
scrapeAlt s = fromMaybe "" . scrapeStringLike s . attr "title" $ "img"

-- |Scrape image from qwantz
scrapeImg :: Text -> Text
scrapeImg s =
    fromMaybe "" .
    scrapeStringLike s .
    html $ "img" @: [hasClass "comic"]
