{-# LANGUAGE OverloadedStrings #-}

module Smbc
  ( smbc
  ) where

import Data.Text
import Data.Text.IO
import Utils

-- |The final html text generated by smbc RSS feed.
smbc :: IO Text
smbc = do
  h <- html
  (title, summary) <- getTitleAndSummary "https://www.smbc-comics.com/rss.php"
  return (template
          [("*title", title)
         , ("*summary", summary)] h)

-- |Get html template. (templates/Smbc.html)
-- TODO make part of a SmbcConfig file.
html :: IO Text
html = Data.Text.IO.readFile "templates/Smbc.html"
