{-# LANGUAGE OverloadedStrings #-}

module Word
  ( word
  ) where

import Data.Text
import Data.Text.IO

import Utils

-- |The final html text generated by merriam-websters word of the day rss feed.
word :: IO Text
word = do
  h <- htmlS
  (title, summary) <- getTitleAndSummary wordFeed
  return (template
          [("*title", title)
         , ("*summary", summary)] h)

-- |Feed URL (in separate function since it is so large.)
wordFeed :: String
wordFeed = "https://www.merriam-webster.com/wotd/feed/rss2"

-- |Template file for word of the day. (templates/Word.html)
htmlS :: IO Text
htmlS = Data.Text.IO.readFile "templates/Word.html"
