name: "Daily"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CONFIG: '${{ secrets.DAILY_CONFIG }}'
      NIXPKGS_ALLOW_BROKEN: 1
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: jhgarner-projects
    - run: nix-build
    - run: |
        cd result
        bin/DailyReporter-exe
