name: "Daily"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CONFIG: '${{ secrets.DAILY_CONFIG }}'
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        name: jhgarner-projects
    - run: nix-build
    - run: |
        cd result
        dailyReporter/bin/DailyReporter-exe
