name: "UpdateCache"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: jhgarner-projects
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
      env:
        NIXPKGS_ALLOW_BROKEN: 1
